config/routes.rb
RjfrcWeb::Application.routes.draw do
  resources :issues
  resources :events
  resources :blog_posts
  resources :users
  resources :home
  
  #Team
  get '/team' => 'team#about-us'
  get '/team/about-us' => 'team#about-us'
  get '/team/about-first' => 'team#about-first'
  # get '/team/contact' => 'team#contact'
  #Community
  get '/community' => 'community#outreach'
  get '/community/outreach' => 'community#outreach'
  get '/community/events' => 'community#events'
  get '/community/sponsors' => 'community#sponsors'
  get '/community/contact' => 'community#contact'
  #Sliders
  match '/slider1' => 'slider1#index'
  match '/slider2' => 'slider2#index'
  # Users
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/login' => 'users#login'
  post '/login' => 'users#login'
  get '/logout' => 'users#logout'
  get '/users/new' => 'users#new'
  post '/users/new' => 'users#create'
  match '/users(/:id)' => 'users#show'
  # Blog
  match '/' => redirect("/home")  
  get '/blog' => 'blog_posts#index'
  get '/blog/new' => 'blog_posts#new'
  match '/blog(/:id)' => 'blog_posts#show'
  # Issues
  match '/issues(/:id)' => 'issues#show'
  # Calendar
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/calendar' => 'calendar#index'
  # Build
  get '/build' => 'build#about'
  get '/build/about' => 'build#about'
  get '/build/garage' => 'build#2013'
  get '/build/garage/2013' => 'build#2013'
  get '/build/garage/2012' => 'build#2012'
  get '/build/garage/2011' => 'build#2011'
  # Code
  get '/code' => 'code#git'
  get '/code/projects' => 'code#projects'
  get '/code/git' => 'code#git'
  # Admin
  get '/admin' => 'admin#index'
  post '/events(/:id)' => 'events#update_attendance'
  # E-Mail
  post '/events/rsvp' => 'events#rsvp'
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  attr_accessible :description, :watchers, :parent, :subtasks, :name
  serialize :watchers, Array
  serialize :subtasks, Array
  validates :description, presence: true
  validates :name, presence: true
  
  #  belongs_to :parent, :class_name => 'Issue', :foreign_key => 'parent'
  #  has_many :children, :class_name => 'Issue', :foreign_key => 'parent'

  # @@tree_root = Tree::TreeNode.new("Issue Tree Root", nil)

  # def self.add_issue(i)
  #   # Check if issue has a parent
  #   if not i.parent.nil?
  #     # Find appropriate parent node
  #     parent = @@tree_root.detect {|issue| i.parent == issue.content.id }
  #     # Die if parent can't be found
  #     if parent.nil?
  #       return false
  #     else
  #       # Otherwise, insert it into le tree
  #       parent << Tree::TreeNode("#{i.id} - #{i.name}", i)
  #     end
  #   else
  #     # If no parent specified
  #   end
  # end

  # def self.tree_table_html
    
  # end

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  layout "team"
    before_filter :login_required!, only: [:create, :new, :edit, :update, :destroy]
  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @issues }
    end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @issue = Issue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/new
  # GET /issues/new.json
  def new
    @issue = Issue.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/1/edit
  def edit
    @issue = Issue.find(params[:id])
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(params[:issue])

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render json: @issue, status: :created, location: @issue }
      else
        format.html { render action: "new" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /issues/1
  # PUT /issues/1.json
  def update
    @issue = Issue.find(params[:id])

    respond_to do |format|
      if @issue.update_attributes(params[:issue])
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue = Issue.find(params[:id])
    @issue.destroy

    respond_to do |format|
      format.html { redirect_to issues_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
  def index_issue_table
    out = ""
    done = []
    queue.each do |issue|
      unless done.include?(issue)
        out << "<tr>#{issue.id} - #{issue.name}</tr>"
        subtasks = Issue.where(parent: issue.id)
        subtasks.each do |s|
          puts "----#{s.id} - #{s.name}"
          done << s
        end
      end
    end
    
  end
end

app/views/issues/_form.html.erb
<%= form_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= form_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="text">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="text">
    <%= f.label "Parent Task" %>
    <% if Issue.all == [] %>
    No other tasks!
    <% else %>
    <%= select("event", "id", Issue.all.sort {|a, b|  a.id <=> b.id }.collect {|e| [ "Issue #{e.id}", e.id ] }, { :include_blank => false } ) %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<div id="content">
<h1>Editing Issue <%= @issue.id %> - <%= @issue.name %></h1>

<div class="bubble">
<%= form_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="text">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <br />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>
<br />
<br />
</div>

app/views/issues/index.html.erb
<%= stylesheet_link_tag "events" %>
<div id="content">

<h1>Listing issues</h1>

<div class="bubble">
<table class="entry">
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @issues.each do |issue| %>
<% next unless issue.parent.nil? %>
  <tr>
    <td><%= link_to "#{issue.id} - #{issue.name}", issue %></td>
    <td><%= link_to 'Show', issue %></td>
    <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
    <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Issue', new_issue_path %>
</div>
<br />
</div>

app/views/issues/new.html.erb
<h1>New Issue</h1>

<div class="bubble">
<%= form_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="text">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="text">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="text">
    <%= f.label "Parent Task" %>
    <% if Issue.all == [] %>
    No other tasks!
    <% else %>
    <%= select("issue", "parent", Issue.all.sort {|a, b|  a.id <=> b.id }.collect {|e| [ "Issue #{e.id} - #{e.name}", e.id ] }, { :include_blank => true } ) %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', issues_path %>
</div>

app/views/issues/show.html.erb
<%= stylesheet_link_tag "events" %>
<div id="content">
<p id="notice"><%= notice %></p>

<b>Issue <%= @issue.id %> - <%= @issue.name %></b>

<div class="bubble">
<p>
  <%= @issue.description %>
</p>
<p>
<% unless Issue.where(parent: @issue.id) == [] %>
<table class="entry">
<tr><td><b>Children</b></td></tr>
<% Issue.where(parent: @issue.id).each do |issue| %>
  <tr>
    <td><%= link_to "#{issue.id} - #{issue.name}", issue %></td>
    <td><%= link_to 'Show', issue %></td>
    <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
    <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<% end %>
</p>
</div>


<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>
<br />
<br />
</div>