config/routes.rb
RjfrcWeb::Application.routes.draw do
  resources :issues
  resources :events
  resources :blog_posts
  resources :users
  resources :home
  
  #Team
  get '/team' => 'team#about-us'
  get '/team/about-us' => 'team#about-us'
  get '/team/about-first' => 'team#about-first'
  # get '/team/contact' => 'team#contact'
  #Community
  get '/community' => 'community#outreach'
  get '/community/outreach' => 'community#outreach'
  get '/community/events' => 'community#events'
  get '/community/sponsors' => 'community#sponsors'
  get '/community/contact' => 'community#contact'
  #Sliders
  match '/slider1' => 'slider1#index'
  match '/slider2' => 'slider2#index'
  # Users
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  get '/login' => 'users#login'
  post '/login' => 'users#login'
  get '/logout' => 'users#logout'
  get '/users/new' => 'users#new'
  post '/users/new' => 'users#create'
  match '/users(/:id)' => 'users#show'
  # Blog
  match '/' => redirect("/home")  
  get '/blog' => 'blog_posts#index'
  get '/blog/new' => 'blog_posts#new'
  match '/blog(/:id)' => 'blog_posts#show'
  # Issues
  match '/issues(/:id)' => 'issues#show'
  # Calendar
  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  match '/calendar' => 'calendar#index'
  # Build
  get '/build' => 'build#about'
  get '/build/about' => 'build#about'
  get '/build/garage' => 'build#2013'
  get '/build/garage/2013' => 'build#2013'
  get '/build/garage/2012' => 'build#2012'
  get '/build/garage/2011' => 'build#2011'
  # Code
  get '/code' => 'code#git'
  get '/code/projects' => 'code#projects'
  get '/code/git' => 'code#git'
  # Admin
  get '/admin' => 'admin#index'
  post '/events(/:id)' => 'events#update_attendance'
  # E-Mail
  post '/events/rsvp' => 'events#rsvp'
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  attr_accessible :body, :title
  validates :body, presence: true
  validates :title, presence: true

  belongs_to :user


end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  layout "blag"
  before_filter :login_required!, only: [:create, :new, :edit, :update, :destroy]
  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @blog_posts }
    end
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
    @blog_post = BlogPost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @blog_post }
    end
  end

  # GET /blog_posts/new
  # GET /blog_posts/new.json
  def new
    @blog_post = BlogPost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @blog_post }
    end
  end

  # GET /blog_posts/1/edit
  def edit
    @blog_post = BlogPost.find(params[:id])
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(params[:blog_post])
    @blog_post.user = session[:user]
    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, :notice => 'Blog post was successfully created.' }
        format.json { render :json => @blog_post, :status => :created, :location => @blog_post }
      else
        format.html { render :action => "new" }
        format.json { render :json => @blog_post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /blog_posts/1
  # PUT /blog_posts/1.json
  def update
    @blog_post = BlogPost.find(params[:id])

    respond_to do |format|
      if @blog_post.update_attributes(params[:blog_post])
        format.html { redirect_to @blog_post, :notice => 'Blog post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @blog_post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post = BlogPost.find(params[:id])
    @blog_post.destroy

    respond_to do |format|
      format.html { redirect_to blog_posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_posts/_form.html.erb
  <%= form_for(@blog_post) do |f| %>
  <% if @blog_post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

    <ul>
      <% @blog_post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  
  <div class="field">
    <h3>Title</h3>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <h3>Body</h3>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>

app/views/blog_posts/edit.html.erb
<% content_for :page_title do %>
Editing Post
<% end %>

<h1>Editing Post</h1>
<div class="bubble">
  <%= render 'form' %>

  <%= link_to 'Back', @blog_post %> |
  <%= link_to 'Live Blog', blog_posts_path %>
</div>

app/views/blog_posts/index.html.erb
<% content_for :header do -%>
  <%= stylesheet_link_tag "blog" %>
<% end -%>

  <% @blog_posts.reverse.each do |blog_post| %>
  <div id="blog_entry" style="color: #686868;">  
    <h2 class="title"><%= blog_post.title %></h2>
    <%= blog_post.body.html_safe %>
    <br />
    <br />
        Posted by <%= blog_post.user.full %> on <%= blog_post.created_at.to_formatted_s(:short) %> | <%= link_to 'Permalink', blog_post %>
    <% if session[:user] and session[:user].blog_access? %>
    | <%= link_to 'Edit', edit_blog_post_path(blog_post) %>
    | <%= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    <br />
  </div>    
  <% end %>
  
  

app/views/blog_posts/new.html.erb
<div id="content">
<% content_for :page_title do %>
New Post
<% end %>

<%= render 'form' %>

<%= link_to 'Back', blog_posts_path %>
<br />
<br />
</div>

app/views/blog_posts/show.html.erb
<% content_for :page_title do %>
Viewing Post
<% end %>
<div id="content">
  <p id="notice"><%= notice %></p>
  <h1><%= @blog_post.title%></h1>
  
  <p class="entry">
    <%= @blog_post.body.html_safe %>
    <br />
    <br />
    <% if session[:user] %>
    <%= link_to 'Edit', edit_blog_post_path(@blog_post) %> |
    <% end %>
    <%= link_to 'To Live Blog', blog_posts_path %>
  </p>
  
</div>